-- author: Norman Aberin
-- version: v1.0.0
--
-- the following tables are the initial simplified
-- version of the database tables


CREATE TABLE OC_CATEGORIES (
    CATEGORY_ID            number generated by default on null as identity
        primary key,
    CATEGORY               varchar2(255),
    CONSTRAINT uq_category_name unique(CATEGORY)
);

CREATE TABLE OC_COURSES (
    COURSE_ID               number generated by default on null as identity
        primary key,
    COURSE_NAME             varchar2(255) not null,
    COURSE_DESCRIPTION      varchar2(4000) not null,
    COURSE_IMG_LINK         varchar2(4000),
    IS_ACTIVE               number not null check(IS_ACTIVE in (0, 1)),
    CATEGORY_ID             number not null references OC_CATEGORIES(CATEGORY_ID)
);

CREATE TABLE OC_LESSON_SECTIONS (
    LESSON_SECTION_ID       number generated by default on null as identity
        primary key,
    LESSON_SECTION_NAME     varchar2(255) not null,
    LESSON_SECTION_ORDER    number,
    COURSE_ID               number not null references OC_COURSES(COURSE_ID) on delete cascade
);

CREATE TABLE OC_LESSONS (
    LESSON_ID               number generated by default on null as identity
        primary key,
    LESSON_NAME             varchar2(255) not null,
    LESSON_DESCRIPTION      varchar2(255),
    SECTION_ID              number not null
        references OC_LESSON_SECTIONS(LESSON_SECTION_ID) on delete cascade,
    LESSON_ORDER            number not null

);

CREATE TABLE OC_TAGS (
    TAG_ID                  number generated by default on null as identity
        primary key,
    TAG                     varchar2(255),
    CONSTRAINT uq_tag unique(TAG)
);

CREATE TABLE OC_COURSE_TAGS (
    SUB_ID                  number generated by default on null as identity
        primary key,
    TAG_ID                  number not null
        references OC_TAGS(TAG_ID),
    COURSE_ID               number not null
        references OC_COURSES(COURSE_ID) on delete cascade,
    CONSTRAINT uq_course_tag UNIQUE (TAG_ID, COURSE_ID)
);
